version: '3.8'

networks:
  brycekeen-web-network:
    name: brycekeen-web-network
    driver: bridge

services:
  # Database - Running mysql
  # Default Container port number: 3306
  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    networks:
      - brycekeen-web-network
    env_file:
      - ./database/.env
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Backend - Running C# API
  backend:
    build: ./backend                       # Location of dockerfile
    container_name: backend_container
    restart: always
    networks:
      - brycekeen-web-network
    depends_on:
      - db

  # Frontend - Running nginx
  nginx:
    image: nginx
    container_name: nginx_container
    networks:
      - brycekeen-web-network
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro
      - ./frontend/conf.d:/etc/nginx/conf.d:ro

volumes:
  db_data:

