version: '3.8'

networks:
  brycekeen-web-network:
    name: brycekeen-web-network
    driver: bridge

services:
  # Deploying build locally for testing
  nginx:
    image: nginx
    container_name: nginx_container
    restart: always
    networks:
      - brycekeen-web-network
    ports:
      - "3005:3005"
    volumes:
      - ./src/build:/usr/share/nginx/html:ro
      - ./misc/conf.d:/etc/nginx/conf.d:ro
    profiles:
      - build-test

  build-pelican:
    build:
      context: ./src/
      dockerfile: python3.dockerfile
    volumes:
      - ./src/build/:/app/build/
      - ./src/pelican/:/app/pelican/
    profiles:
      - build
    working_dir: /app
    command: ["/bin/bash", "-c", "python3 -m pelican -s /app/pelican/pelicanconf.py"]
